let change = '30 Days Of JavaScript';
console.log(change);
console.log(change.length);
console.log(change.toUpperCase());
console.log(change.toLocaleLowerCase());
console.log(change.substring(3, 4));
console.log(change.substring(3));
console.log(change.includes('Script'));
console.log(change.split());
let companias ='Facebook, Google , Microsoft, Apple, IBM, Oracle, Amazon';
console.log(companias.split(';'));
console.log(change.replace('JavaScript','Node'));
console.log(change.charAt(15));
console.log(change.charCodeAt('J'));
console.log(change.indexOf('a'));
console.log(change.lastIndexOf('a'));
let oracion ='No puedes terminar una oración con porque porque porque es una conjunción';
console.log(oracion.indexOf('porque'));
console.log(oracion.lastIndexOf('porque'));
console.log(oracion.search('porque'));
console.log(change.trim());
console.log(change.startsWith(30));
console.log(change.endsWith('JavaScript'));
let string = '30 Days Of';
console.log(string.concat('JavaScript'));
console.log(change.repeat(2));